name: Automating terraform lint and apply

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_ACCOUNT_ID: 703844615264
      WORK_DIR: terraform/infra/envs/prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::703844615264:role/githuboicd-deploy
          aws-region: eu-west-2

      - name: terraform lint download
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: terraform lint
        run: |
          cd $WORK_DIR
          tflint --init
          tflint

      - name: terraform apply
        run: |
          cd $WORK_DIR
          terraform init
          terraform apply --auto-approve
